services:
#    digitar_assurex.example:
#        class: Digitar\AssurexBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

parameters:
  mon_parametre: ma_valeur

services:
  digitar_assurex.antimineur:
    class: Digitar\AssurexBundle\Antimineur\DigitarAntimineur