<?php

namespace Digitar\AssurexBundle\Repository;

/**
 * TypeContratMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContratMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
